# Generated by Django 3.2.5 on 2022-04-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('BIZPLC_NM', models.CharField(max_length=30, verbose_name='사업장명')),
                ('SIGUN_NM', models.CharField(max_length=20, verbose_name='시군명')),
                ('BSN_STATE_NM', models.BooleanField(verbose_name='영업상태명')),
                ('REFINE_ROADNM_ADDR', models.CharField(max_length=50, verbose_name='소재지도로명주소')),
                ('REFINE_WGS84_LAT', models.FloatField(verbose_name='WGS84위도')),
                ('REFINE_WGS84_LOGT', models.FloatField(verbose_name='WGS84경도')),
                ('hotel_rate', models.FloatField(verbose_name='평점')),
                ('hotel_comment', models.CharField(max_length=200, verbose_name='요약설명')),
            ],
            options={
                'verbose_name': '호텔',
                'verbose_name_plural': '호텔(들)',
                'db_table': 'SLHJ_hotel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='유저ID')),
                ('user_password', models.CharField(max_length=20, verbose_name='유저비밀번호')),
                ('user_type', models.IntegerField(verbose_name='유저타입')),
                ('user_email', models.EmailField(max_length=100, verbose_name='유저이메일')),
                ('user_phonenum', models.CharField(max_length=15, verbose_name='유저전화번호')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자(들)',
                'db_table': 'SLHJ_user',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('vacation_id', models.AutoField(primary_key=True, serialize=False)),
                ('SIGUN_NM', models.CharField(max_length=20, verbose_name='시군명')),
                ('TURSM_INFO_NM', models.CharField(max_length=20, verbose_name='관광지명')),
                ('SM_RE_ADDR', models.CharField(max_length=50, verbose_name='소재주소')),
                ('TELNO', models.CharField(max_length=15, verbose_name='전화번호')),
                ('REFINE_WGS84_LAT', models.FloatField(verbose_name='정제WGS84위도')),
                ('REFINE_WGS84_LOGT', models.FloatField(verbose_name='정제WGS84경도')),
                ('vacation_comment', models.CharField(max_length=200, verbose_name='요약설명')),
                ('vacation_price', models.IntegerField(verbose_name='여행지가격')),
                ('vacation_rate', models.FloatField(verbose_name='여행지평점')),
                ('vacation_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.user')),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지(들)',
                'db_table': 'SLHJ_vacation',
            },
        ),
        migrations.CreateModel(
            name='Hotel_image',
            fields=[
                ('hotel_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SLHJ.hotel')),
                ('hotel_image_title', models.CharField(max_length=100, verbose_name='파일이름')),
                ('hotel_image_file_path', models.FileField(upload_to='UploadedFiles/', verbose_name='파일경로')),
                ('hotel_image_originname', models.CharField(max_length=100, verbose_name='원본이름')),
            ],
            options={
                'verbose_name': '호텔사진',
                'db_table': 'SLHJ_hotel_image',
            },
        ),
        migrations.CreateModel(
            name='Vacation_image',
            fields=[
                ('vacation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SLHJ.vacation')),
                ('vacation_image_title', models.CharField(max_length=100, verbose_name='파일이름')),
                ('vacation_image_file_path', models.FileField(upload_to='UploadedFiles/', verbose_name='파일경로')),
                ('vacation_image_originname', models.CharField(max_length=100, verbose_name='원본이름')),
            ],
            options={
                'verbose_name': '여행지사진',
                'db_table': 'SLHJ_vacation_image',
            },
        ),
        migrations.CreateModel(
            name='Vacation_review',
            fields=[
                ('vacation_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacation_review_content', models.CharField(max_length=100, verbose_name='리뷰내용')),
                ('vacation_review_rate', models.IntegerField(verbose_name='리뷰평점')),
                ('vacation_review_date', models.DateTimeField(auto_now_add=True, verbose_name='리뷰등록시간')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.user')),
                ('vacation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.vacation')),
            ],
            options={
                'verbose_name': '여행지리뷰',
                'verbose_name_plural': '여행지리뷰(들)',
                'db_table': 'SLHJ_vacation_review',
            },
        ),
        migrations.CreateModel(
            name='Vacation_reserve',
            fields=[
                ('vacation_reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacation_reserve_people', models.IntegerField(verbose_name='예약인원')),
                ('vacation_reserve_date', models.DateField(verbose_name='예약날짜')),
                ('vacation_reserve_username', models.CharField(max_length=20, verbose_name='예약자명')),
                ('vacation_reserve_phonenum', models.CharField(max_length=15, verbose_name='핸드폰번호')),
                ('vacation_reserve_price', models.IntegerField(verbose_name='결제금액')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.user')),
                ('vacation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.vacation')),
            ],
            options={
                'verbose_name': '여행지예약',
                'verbose_name_plural': '여행지예약(들)',
                'db_table': 'SLHJ_vacation_reserve',
            },
        ),
        migrations.CreateModel(
            name='Hotel_room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=20, verbose_name='방타입')),
                ('room_price', models.IntegerField(verbose_name='방가격')),
                ('room_people', models.IntegerField(verbose_name='사용인원')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.hotel')),
            ],
            options={
                'verbose_name': '호텔방',
                'verbose_name_plural': '호텔방(들)',
                'db_table': 'SLHJ_hotel_room',
            },
        ),
        migrations.CreateModel(
            name='Hotel_review',
            fields=[
                ('hotel_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_review_content', models.CharField(max_length=100, verbose_name='리뷰내용')),
                ('hotel_review_rate', models.IntegerField(verbose_name='리뷰평점')),
                ('hotel_review_date', models.DateField(verbose_name='리뷰등록시간')),
                ('hotel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SLHJ.hotel')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.user')),
            ],
            options={
                'verbose_name': '호텔리뷰',
                'verbose_name_plural': '호텔예약(들)',
                'db_table': 'SLHJ_hotel_review',
            },
        ),
        migrations.CreateModel(
            name='Hotel_reserve',
            fields=[
                ('hotel_reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_reserve_people', models.IntegerField(verbose_name='예약인원')),
                ('hotel_reserve_username', models.CharField(max_length=20, verbose_name='예약자명')),
                ('hotel_reserve_phonenum', models.CharField(max_length=15, verbose_name='핸드폰번호')),
                ('hotel_reserve_startdate', models.DateField(verbose_name='체크인날짜')),
                ('hotel_reserve_enddate', models.DateField(verbose_name='체크아웃날짜')),
                ('hotel_reserve_price', models.IntegerField(verbose_name='결제금액')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.user')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.hotel_room')),
            ],
            options={
                'verbose_name': '호텔예약',
                'verbose_name_plural': '호텔예약(들)',
                'db_table': 'SLHJ_hotel_reserve',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHJ.user'),
        ),
    ]
